// from https://www.musicgenreslist.com/#music-genre-list
export const GENRE_LIST = [
    "Alternative",
    "Anime",
    "Blues",
    "Children's Music",
    "Classical",
    "Contemporary Classical",
    "Comedy",
    "Buy me a Cuppa",
    "Country",
    "Dance",
    "Disney",
    "Easy Listening",
    "Electronic",
    "Enka",
    "French Pop",
    "German Folk",
    "German Pop",
    "Fitness & Workout",
    "Hip-Hop/Rap",
    "Holiday",
    "Indie Pop",
    "Industrial",
    "Christian & Gospel",
    "Instrumental",
    "J-Pop ",
    "Jazz",
    "K-Pop",
    "Karaoke",
    "Kayokyoku",
    "Latin",
    "Metal",
    "New Age",
    "Opera",
    "Pop",
    "R&B/Soul",
    "Reggae",
    "Rock",
    "Rockabilly",
    "Soundtrack",
    "Spoken Word",
    "Tex-Mex / Tejano",
    "Vocal",
    "World",
]