// from https://www.musicgenreslist.com/#music-genre-list
export const GENRE_LIST = [
  "Alternative",
  "Anime",
  "Blues",
  "Country",
  "Dance",
  "Disney",
  "Electronic/EDM",
  "Funk/Disco",
  "Global",
  "Gospel",
  "Hip-Hop",
  "Holiday",
  "Indie",
  "J-Pop",
  "Jazz",
  "K-Pop",
  "Latin",
  "Metal",
  "New Age",
  "Other",
  "Pop",
  "R&B/Soul",
  "Rap",
  "Rock",
  "TV/Movies",
];