import Head from "next/head";
import styles from "../styles/Home.module.css";
import Landing from "../components/home/landing";
import { createServerSupabaseClient } from "@supabase/auth-helpers-nextjs";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MicDrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./appicon.png" />
      </Head>
      <main className={`${styles.main}`}>
        <Landing />
      </main>
    </div>
  );
}

export const getServerSideProps = async (ctx) => {
  // Create authenticated Supabase Client
  const supabase = createServerSupabaseClient(ctx);
  // Check if we have a session
  const {
    data: { session },
  } = await supabase.auth.getSession();

  if (!session)
    return {
      redirect: {
        destination: "/",
        permanent: false,
      },
    };

  return {
    props: {
      initialSession: session,
      user: session.user,
    },
  };
};
