import Head from "next/head";
import styles from "../styles/Home.module.css";
import Landing from "../components/home/landing";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>MicDrop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./appicon.png" />
      </Head>
      <main className={styles.main}>
        <Landing />
      </main>
    </div>
  );
}
